spring:

  application:

  datasource:
    url: jdbc:mysql://${DB_HOST_NAME:database}:${DB_PORT_NUMBER:3306}/${DB_NAME:quietspace}
    username: ${DB_USER_USERNAME:quietspace_user}
    password: ${DB_USER_PASSWORD}

    hikari:
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        useLocalSessionState: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        elideSetAutoCommits: true
        maintainTimeStats: false
      pool-name: RestDB-Pool
      maximum-pool-size: 5

  jpa:
    properties:
      hibernate:
        show_sql: false
        format_sql: false
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true
    baseline-on-migrate: true
    validate-on-migrate: true

  sql:
    init:
      mode: never

server:
  port: ${SERVER_PORT_NUMBER:8080}
