spring:
  servlet.multipart:
    enabled: true
    max-file-size: 3MB
    max-request-size: 10MB
  custom:
    admin-password: ${ADMIN_PASSWORD}
  profiles:
    default: default
    active: ${ACTIVE_PROFILE}
  mail:
    host: ${MAILDEV_HOST}
    port: ${MAILDEV_PORT}
    username: thural
    password: thural
    properties:
      mail:
        smtp:
          trust: "*"
          auth: true
        starttls:
          enabled: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000
  application:
    name: quietspace-backend
    security:
      jwt:
        secret-key: ${JWT_SECRET_KEY}
        expiration: 600000
        refresh-token:
          expiration: 86400000
    mailing:
      frontend:
        activation-url: ${ACTIVATION_URL}