spring:
  mail:
    host: smtp.postmarkapp.com
    port: 587
    username: ${POSTMARK_SERVER_TOKEN}
    password: ${POSTMARK_SERVER_TOKEN}
    properties:
      mail:
        smtp:
          auth: true
        starttls:
          enabled: true
