spring:
  application:
    mailing:
      frontend:
        activation-url: http://localhost:3000/activate
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/quietspace
    username: ${DB_USER_USERNAME}
    password: ${DB_USER_PASSWORD}
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
      jakarta:
        persistence:
          schema-generation:
            scripts:
              action: create
              create-target: src/main/resources/db.migration/schema/generated.sql
    hibernate:
      ddl-auto: update
    show-sql: true
  flyway:
    enabled: false

logging:
  level:
    root: INFO
    org.springframework.messaging: INFO
    org.springframework.web.socket: INFO
    org.hibernate.orm.jdbc.bind: ERROR
    dev.thural.quietspace.service: INFO
    org.springframework.security: INFO
    org.hibernate.sql: ERROR
    org.springframework.web.servlet.handler.HandlerMappingIntrospector: ERROR
  logback:
    rollingpolicy:
      max-file-size: 2MB
      max-history: 3

server:
  port: 8080
