spring:
  threads:
    virtual:
      enabled: true
  config:
    import: optional:file:.env
  servlet.multipart:
    enabled: true
    max-file-size: 3MB
    max-request-size: 10MB
  custom:
    admin-password: ${ADMIN_PASSWORD}
  profiles:
    default: default
    active: dev
  mail:
    host: ${MAILDEV_HOST}
    port: ${MAILDEV_PORT}
    username: ${MAIL_USERNAME:thural}
    password: ${MAIL_PASSWORD:thural}
    properties:
      mail:
        smtp:
          trust: "*"
          auth: true
        starttls:
          enabled: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    open-in-view: false
  flyway:
    baseline-description: "init"
    baseline-version: 0
    locations: classpath:db/migration/structure, classpath:db/migration/data
  application:
    name: quietspace-backend
    security:
      jwt:
        secret-key: ${JWT_SECRET_KEY}
        expiration: 600000
        refresh-token:
          expiration: 86400000
    mailing:
      frontend:
        activation-url: ${ACTIVATION_URL}

springwolf:
  docket:
    base-package: dev.thural.quietspace
    info:
      title: QuietSpace WebSocket API
      version: 1.0.0

springdoc:
  use-fqn: true