"""add blocked_users table

Revision ID: 0b0ea170c0a7
Revises: 258cffccf9de
Create Date: 2026-07-06 19:37:44.382373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


revision: str = '0b0ea170c0a7'
down_revision: Union[str, None] = '258cffccf9de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blocked_users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('blocker_id', sa.Uuid(), nullable=False),
    sa.Column('blocked_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['blocked_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['blocker_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('blocker_id', 'blocked_id', name='uq_blocked_user_pair')
    )
    op.create_index(op.f('ix_blocked_users_blocked_id'), 'blocked_users', ['blocked_id'], unique=False)
    op.create_index(op.f('ix_blocked_users_blocker_id'), 'blocked_users', ['blocker_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_blocked_users_blocker_id'), table_name='blocked_users')
    op.drop_index(op.f('ix_blocked_users_blocked_id'), table_name='blocked_users')
    op.drop_table('blocked_users')
    # ### end Alembic commands ###
