"""add repost fields to post

Revision ID: 258cffccf9de
Revises: d8174bcf9606
Create Date: 2026-07-06 11:00:49.361088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


revision: str = '258cffccf9de'
down_revision: Union[str, None] = 'd8174bcf9606'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('repost_text', sqlmodel.sql.sqltypes.AutoString(length=280), nullable=True))
    op.add_column('post', sa.Column('repost_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_post_repost_id'), 'post', ['repost_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_post_repost_id'), table_name='post')
    op.drop_column('post', 'repost_id')
    op.drop_column('post', 'repost_text')
    # ### end Alembic commands ###
