"""add poll tables

Revision ID: add_poll_tables
Revises: c008ed6aecb7
Create Date: 2026-07-06 20:30:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


revision: str = 'add_poll_tables'
down_revision: Union[str, None] = 'c008ed6aecb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('polls',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('post_id', sa.Uuid(), nullable=False),
    sa.Column('question', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_polls_post_id'), 'polls', ['post_id'], unique=False)
    
    op.create_table('poll_options',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('poll_id', sa.Uuid(), nullable=False),
    sa.Column('option_text', sa.String(), nullable=False),
    sa.Column('vote_count', sa.Integer(), nullable=False, server_default='0'),
    sa.ForeignKeyConstraint(['poll_id'], ['polls.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_poll_options_poll_id'), 'poll_options', ['poll_id'], unique=False)
    
    op.create_table('poll_votes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('poll_option_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('voted_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['poll_option_id'], ['poll_options.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('poll_option_id', 'user_id', name='uq_poll_vote')
    )
    op.create_index(op.f('ix_poll_votes_poll_option_id'), 'poll_votes', ['poll_option_id'], unique=False)
    op.create_index(op.f('ix_poll_votes_user_id'), 'poll_votes', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_poll_votes_user_id'), table_name='poll_votes')
    op.drop_index(op.f('ix_poll_votes_poll_option_id'), table_name='poll_votes')
    op.drop_table('poll_votes')
    op.drop_index(op.f('ix_poll_options_poll_id'), table_name='poll_options')
    op.drop_table('poll_options')
    op.drop_index(op.f('ix_polls_post_id'), table_name='polls')
    op.drop_table('polls')
    # ### end Alembic commands ###
