"""add depth and composite index to comment

Revision ID: c008ed6aecb7
Revises: 0b0ea170c0a7
Create Date: 2026-07-06 19:51:38.823442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


revision: str = 'c008ed6aecb7'
down_revision: Union[str, None] = '0b0ea170c0a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('depth', sa.Integer(), nullable=False))
    op.create_index('ix_comment_post_parent', 'comment', ['post_id', 'parent_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_comment_post_parent', table_name='comment')
    op.drop_column('comment', 'depth')
    # ### end Alembic commands ###
