version: '3.8'
services:

  quietspace-monolith-db:
    image: mysql:8.0
    restart: on-failure
    volumes:
      - quietspace_monolith_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER_USERNAME}
      MYSQL_PASSWORD: ${DB_USER_PASSWORD}
    networks:
      - monolith-network
    ports:
      - "3306:3306"

  quietspace-monolith-dev:
    build:
      context: ../..
      dockerfile: ./infrastructure/docker/buildfiles/dev/Dockerfile
    image: thural/quietspace:monolith-dev
    depends_on:
      - quietspace-monolith-db
    env_file:
      - ./.env
    networks:
      - monolith-network
    ports:
      - "8080:8080"
    volumes:
      - ./:/app
      - /target

  mail-dev:
    container_name: mail-dev
    image: maildev/maildev
    networks:
      - monolith-network
    ports:
      - "1080:1080"
      - "1025:1025"

volumes:
  quietspace_monolith_data:

networks:
  monolith-network:
    name: monolith-network
    driver: bridge
    external: true