version: '3.8'

services:

  quietspace-monolith:
    entrypoint: [
      "java",
      "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005",
      "-jar", "application.jar"
    ]
    ports:
      - "${SERVER_PORT_NUMBER}:8080"
      - "5005:5005"
