spring:
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}

email:
  provider:
    url: ${EMAIL_PROVIDER_URL:https://api.resend.com}
    key: ${EMAIL_API_KEY}
