from enum import Enum


class ErrorCode(str, Enum):
    AUTH_FAILED = "AUTH_FAILED"
    FORBIDDEN = "FORBIDDEN"
    NOT_FOUND = "NOT_FOUND"
    VALIDATION_ERROR = "VALIDATION_ERROR"
    RATE_LIMITED = "RATE_LIMITED"
    INTERNAL_ERROR = "INTERNAL_ERROR"


class WebSocketEventType(str, Enum):
    JOIN_CHAT = "JOIN_CHAT"
    LEAVE_CHAT = "LEAVE_CHAT"
    NEW_MESSAGE = "NEW_MESSAGE"
    DELETE_MESSAGE = "DELETE_MESSAGE"
    SEEN_MESSAGE = "SEEN_MESSAGE"
    TYPING = "TYPING"
    CHAT_CREATED = "CHAT_CREATED"
    USER_ONLINE = "USER_ONLINE"
    USER_OFFLINE = "USER_OFFLINE"
    NOTIFICATION = "NOTIFICATION"
    NOTIFICATION_READ = "NOTIFICATION_READ"
    SYSTEM = "SYSTEM"
    ERROR = "ERROR"
