name: Qodana
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  qodana:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}  
          fetch-depth: 0  

      - name: 'Qodana Scan'
        id: qodana-scan
        uses: JetBrains/qodana-action@v2026.1
        continue-on-error: true 
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN_144127475 }}
          QODANA_ENDPOINT: 'https://qodana.cloud'
        with:
          pr-mode: false
          use-caches: true 
